# Generated by Django 3.1.5 on 2021-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('category', models.CharField(default='Undefined', max_length=20)),
                ('image', models.ImageField(upload_to='img')),
                ('qout', models.TextField()),
            ],
        ),
    ]
