# Generated by Django 3.1.5 on 2021-05-21 22:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210521_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qout',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='media'),
        ),
    ]
